language: node_js
node_js: stable
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script: 
  - npm run build
after_success:
  - cd dist
  - echo "dev.abckey.com" > CNAME
  - cp index.html 404.html  
  - git init  
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"  
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
branches:
  only:
    - master
