language: node_js
node_js: stable
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script: 
  - npm run build
after_script:
  - cd docs
  - echo "${CNAME}" > CNAME
  - cp index.html 404.html
  - git init  
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m ":-)"
  - git push -f -q "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
deploy:
  github_token: $GH_TOKEN
  provider: pages
  skip_cleanup: true
  deployment_file: true
  keep_history: true
  verbose: true
branches:
  only:
    - master
