name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
          ls
          cp ./dist/index.html ./dist/404.html
          echo "pro.abckey.com" > ./dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@master
        with:
          SSH: true
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
